"""
PropertyPulse — Formal Metric Registry

Single source of truth for every metric's capabilities. Consumed by
helpers.metric() to enrich API responses with explicit status fields
(comparison_status, trend_status, map_binding), and by
build_metric_contract() to produce the nested Metric contract.

Rules:
- Every metric returned by any tab service MUST have an entry here.
- supports_parent = True means parent comparison is *meaningful* for
  this metric, even if not yet implemented. The runtime comparison_status
  will distinguish "comparable" (has parent value) from "not_modelled_yet"
  (supports parent but value not computed).
- supports_parent = False means comparison is not meaningful (categorical,
  composite summary, etc.). Runtime comparison_status = "not_comparable".
- supports_trend = True means historical time series exists or could exist.
- map_binding declares the map layer this metric is associated with.
  Format: "none" | "point_layer:<layer_id>" | "area_layer:<layer_id>"
- status: "core" (default visible), "detail_only" (expanded only),
  "persona_only" (used in fit scoring / summaries only).
- decision_question: user-facing question this metric helps answer.
- metric_family: grouping key for section summaries.
- interpretation_direction: "lower_is_better" | "higher_is_better" | "neutral".
- quality_notes: optional data quality caveat string.
- source_tables: list of DB tables this metric reads from.
- short_label: concise label for space-constrained UI (map tooltips, badges).
- value_type: semantic value type for formatting. One of:
    "currency", "currency_density", "percentage", "percentage_change",
    "count", "rate", "score", "distance", "level", "categorical", "scalar".
"""

METRIC_REGISTRY = {
    # -----------------------------------------------------------------------
    # Tab 1: Property & Market
    # -----------------------------------------------------------------------
    "avg_price": {
        "section": "Property & Market",
        "label": "Average Sale Price",
        "description": "True AVG from raw transactions (13m window)",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": True,
        "map_binding": "area_layer:choropleth_avg_price",
        "unit": "GBP",
        "status": "core",
        "sort_priority": 1,
        "decision_question": "How expensive is it to buy here?",
        "metric_family": "property_prices",
        "interpretation_direction": "lower_is_better",
        "quality_notes": None,
        "source_tables": ["core_property_transactions"],
    },
    "median_price": {
        "section": "Property & Market",
        "label": "Median House Price",
        "description": "PERCENTILE_CONT(0.5) on raw transactions",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": True,
        "map_binding": "area_layer:choropleth_median_price",
        "unit": "GBP",
        "status": "core",
        "sort_priority": 2,
        "decision_question": "What is the typical purchase price here?",
        "metric_family": "property_prices",
        "interpretation_direction": "lower_is_better",
        "quality_notes": None,
        "source_tables": ["core_property_transactions"],
    },
    "price_per_sqft": {
        "section": "Property & Market",
        "label": "Price per Sqft",
        "description": "Avg price / floor area from EPC-matched transactions (2010-2025)",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": True,
        "map_binding": "area_layer:choropleth_price_per_sqft",
        "unit": "GBP/sqft",
        "status": "core",
        "sort_priority": 3,
        "decision_question": "How expensive is space here?",
        "metric_family": "property_prices",
        "interpretation_direction": "lower_is_better",
        "quality_notes": "Depends on availability of matched floor-area records from EPC data.",
        "source_tables": ["core_property_transactions", "core_epc_domestic"],
    },
    "transaction_volume": {
        "section": "Property & Market",
        "label": "Transaction Volume",
        "description": "Per-LSOA normalized residential sales (last 12 months)",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": True,
        "map_binding": "point_layer:sold_price",
        "unit": "sales/LSOA",
        "status": "core",
        "sort_priority": 4,
        "decision_question": "How active is the local sales market?",
        "metric_family": "market_activity",
        "interpretation_direction": "higher_is_better",
        "quality_notes": None,
        "source_tables": ["core_property_transactions"],
    },
    "freehold_leasehold": {
        "section": "Property & Market",
        "label": "Freehold vs Leasehold",
        "description": "Percentage freehold by transaction count",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "% freehold",
        "status": "core",
        "sort_priority": 5,
        "decision_question": "What tenure mix dominates the local housing market?",
        "metric_family": "tenure_mix",
        "interpretation_direction": "neutral",
        "quality_notes": None,
        "source_tables": ["core_property_transactions"],
    },
    "new_build_proportion": {
        "section": "Property & Market",
        "label": "New Build Proportion",
        "description": "Percentage new build with 10-year trend",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": True,
        "map_binding": "none",
        "unit": "%",
        "status": "core",
        "sort_priority": 6,
        "decision_question": "How much of the local market is newly built housing?",
        "metric_family": "housing_supply",
        "interpretation_direction": "neutral",
        "quality_notes": "Land Registry new-build flags may undercount conversions and some redevelopments.",
        "source_tables": ["core_property_transactions"],
    },
    "price_trend_yoy": {
        "section": "Property & Market",
        "label": "Price Trend (YoY)",
        "description": "HPI year-on-year change. LAD-level only",
        "local_grain": "lad",
        "supports_parent": True,
        "supports_trend": True,
        "map_binding": "none",
        "unit": "%",
        "status": "core",
        "sort_priority": 7,
        "decision_question": "Are values rising or falling here?",
        "metric_family": "property_prices",
        "interpretation_direction": "higher_is_better",
        "quality_notes": "ONS/Land Registry HPI is only published at local-authority level.",
        "source_tables": ["core_hpi_lad"],
    },
    "median_rent": {
        "section": "Property & Market",
        "label": "Median Monthly Rent",
        "description": "VOA PRMS. LAD-level only",
        "local_grain": "lad",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "GBP/month",
        "status": "core",
        "sort_priority": 8,
        "decision_question": "How expensive is it to rent here?",
        "metric_family": "rents",
        "interpretation_direction": "lower_is_better",
        "quality_notes": None,
        "source_tables": ["core_voa_rents_lad"],
    },
    "gross_yield": {
        "section": "Property & Market",
        "label": "Gross Rental Yield",
        "description": "Annual rent / median price. LAD/county only",
        "local_grain": "lad",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "%",
        "status": "core",
        "sort_priority": 9,
        "decision_question": "How attractive is this area for rental investment?",
        "metric_family": "investment",
        "interpretation_direction": "higher_is_better",
        "quality_notes": "Suppressed for postcode and ward searches because rent data is LAD-level only.",
        "source_tables": ["core_voa_rents_lad", "core_property_transactions"],
    },
    "affordability": {
        "section": "Property & Market",
        "label": "Rent Affordability",
        "description": "Rent as % of median earnings. LAD/county only",
        "local_grain": "lad",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "% of income",
        "status": "core",
        "sort_priority": 10,
        "decision_question": "Can a typical household afford to live here?",
        "metric_family": "affordability",
        "interpretation_direction": "lower_is_better",
        "quality_notes": None,
        "source_tables": ["core_voa_rents_lad", "core_earnings_lad"],
    },
    "median_earnings": {
        "section": "Property & Market",
        "label": "Median Annual Earnings",
        "description": "ASHE workplace earnings. LAD-level only",
        "local_grain": "lad",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "GBP/year",
        "status": "core",
        "sort_priority": 11,
        "decision_question": "What does a typical local income look like?",
        "metric_family": "earnings",
        "interpretation_direction": "higher_is_better",
        "quality_notes": "ONS ASHE earnings are only available at local-authority level.",
        "source_tables": ["core_earnings_lad"],
    },
    "investment_grade": {
        "section": "Property & Market",
        "label": "Investment Grade",
        "description": "Composite: yield + HPI growth. LAD/county only",
        "local_grain": "lad",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "grade",
        "status": "core",
        "sort_priority": 12,
        "decision_question": "How investable does this area look on the current evidence?",
        "metric_family": "investment",
        "interpretation_direction": "higher_is_better",
        "quality_notes": "Heuristic synthesis; should be presented as an interpretation aid.",
        "source_tables": ["core_voa_rents_lad", "core_hpi_lad", "core_property_transactions"],
    },
    "epc_energy_score": {
        "section": "Property & Market",
        "label": "EPC Energy Score",
        "description": "Weighted average EPC score from A-G distribution",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "area_layer:choropleth_epc_score",
        "unit": "score",
        "status": "core",
        "sort_priority": 13,
        "decision_question": "How energy-efficient is the local housing stock?",
        "metric_family": "energy_efficiency",
        "interpretation_direction": "higher_is_better",
        "quality_notes": None,
        "source_tables": ["core_epc_lsoa"],
    },
    "epc_rating_c_plus": {
        "section": "Property & Market",
        "label": "EPC Rated C or Above",
        "description": "Percentage of properties with EPC C+",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "%",
        "status": "detail_only",
        "sort_priority": 14,
        "decision_question": "How large is the energy-efficient share of the local housing stock?",
        "metric_family": "energy_efficiency",
        "interpretation_direction": "higher_is_better",
        "quality_notes": None,
        "source_tables": ["core_epc_lsoa"],
    },

    # -----------------------------------------------------------------------
    # Tab 2: Lifestyle & Connectivity
    # -----------------------------------------------------------------------
    "fifteen_min_score": {
        "section": "Lifestyle & Connectivity",
        "label": "15-Minute Score",
        "description": "Composite: 10 pts per amenity type present within 1km",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "score /100",
        "status": "core",
        "sort_priority": 1,
        "decision_question": "How self-sufficient is day-to-day life here?",
        "metric_family": "amenities",
        "interpretation_direction": "higher_is_better",
        "quality_notes": None,
        "source_tables": ["core_osm_amenities"],
    },
    "amenities_15min": {
        "section": "Lifestyle & Connectivity",
        "label": "15-Minute Amenities (1km)",
        "description": "Count of amenities within 1km or area boundary",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "count",
        "status": "core",
        "sort_priority": 2,
        "decision_question": "How many useful day-to-day amenities are nearby?",
        "metric_family": "amenities",
        "interpretation_direction": "higher_is_better",
        "quality_notes": None,
        "source_tables": ["core_osm_amenities"],
    },
    "nearest_station": {
        "section": "Lifestyle & Connectivity",
        "label": "Nearest Station",
        "description": "Distance to nearest rail/metro station. Postcode only",
        "local_grain": "postcode_only",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "point_layer:station",
        "unit": "metres",
        "status": "core",
        "sort_priority": 3,
        "decision_question": "How quickly can you access public transport?",
        "metric_family": "transport_access",
        "interpretation_direction": "lower_is_better",
        "quality_notes": "Only emitted for point-like searches.",
        "source_tables": ["core_transport_stops"],
    },
    "stations_in_area": {
        "section": "Lifestyle & Connectivity",
        "label": "Rail/Metro Stations in Area",
        "description": "Station count within area boundary. Area mode only",
        "local_grain": "area_only",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "point_layer:station",
        "unit": "count",
        "status": "core",
        "sort_priority": 3,
        "decision_question": "How strong is public transport access across the wider area?",
        "metric_family": "transport_access",
        "interpretation_direction": "higher_is_better",
        "quality_notes": "Only emitted for area-style searches.",
        "source_tables": ["core_transport_stops"],
    },
    "ptal_score": {
        "section": "Lifestyle & Connectivity",
        "label": "Public Transport (PTAL)",
        "description": "TfL Public Transport Accessibility Level. London only",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "level",
        "status": "core",
        "sort_priority": 4,
        "decision_question": "How strong is public transport accessibility here?",
        "metric_family": "transport_access",
        "interpretation_direction": "higher_is_better",
        "quality_notes": "Most meaningful in London and PTAL-covered geographies.",
        "source_tables": ["core_ptal_lsoa"],
    },
    "connectivity_index": {
        "section": "Lifestyle & Connectivity",
        "label": "Connectivity Index",
        "description": "Composite: rail + bus + broadband + amenity. Non-London only",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "score /100",
        "status": "core",
        "sort_priority": 5,
        "decision_question": "How well connected does this area feel overall?",
        "metric_family": "connectivity",
        "interpretation_direction": "higher_is_better",
        "quality_notes": None,
        "source_tables": ["core_transport_stops", "core_broadband_postcode", "core_osm_amenities"],
    },
    "ev_chargers": {
        "section": "Lifestyle & Connectivity",
        "label": "EV Chargers (1km)",
        "description": "EV charge points within 1km or area boundary",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "point_layer:ev_charger",
        "unit": "count",
        "status": "core",
        "sort_priority": 6,
        "decision_question": "How convenient is EV charging locally?",
        "metric_family": "transport_infrastructure",
        "interpretation_direction": "higher_is_better",
        "quality_notes": None,
        "source_tables": ["core_ev_chargers"],
    },
    "broadband": {
        "section": "Lifestyle & Connectivity",
        "label": "Broadband Coverage",
        "description": "Ofcom gigabit-capable coverage percentage",
        "local_grain": "lad",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "% gigabit",
        "status": "core",
        "sort_priority": 7,
        "decision_question": "How well connected is this area digitally?",
        "metric_family": "connectivity",
        "interpretation_direction": "higher_is_better",
        "quality_notes": None,
        "source_tables": ["core_broadband_postcode"],
    },
    "cycling": {
        "section": "Lifestyle & Connectivity",
        "label": "Cycling to Work",
        "description": "Census TS061 cycling commuters percentage",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "% commuters",
        "status": "core",
        "sort_priority": 8,
        "decision_question": "How cycle-friendly does commuting here appear to be?",
        "metric_family": "active_travel",
        "interpretation_direction": "higher_is_better",
        "quality_notes": None,
        "source_tables": ["core_cycling_lsoa"],
    },
    "commute_distance": {
        "section": "Lifestyle & Connectivity",
        "label": "Work From Home Rate",
        "description": "Census TS058 WFH percentage with distance bands",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "% of workers",
        "status": "core",
        "sort_priority": 9,
        "decision_question": "How remote-friendly does the local work pattern look?",
        "metric_family": "commuting",
        "interpretation_direction": "higher_is_better",
        "quality_notes": None,
        "source_tables": ["core_census_lsoa"],
    },
    "mobile_coverage": {
        "section": "Lifestyle & Connectivity",
        "label": "Mobile Coverage (4G/5G)",
        "description": "Ofcom 4G outdoor coverage. LAD-level data",
        "local_grain": "lad",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "% 4G outdoor",
        "status": "core",
        "sort_priority": 10,
        "decision_question": "How reliable is mobile coverage here?",
        "metric_family": "connectivity",
        "interpretation_direction": "higher_is_better",
        "quality_notes": "LAD-based coverage as the best available proxy.",
        "source_tables": ["core_mobile_coverage_lad"],
    },

    # -----------------------------------------------------------------------
    # Tab 3: Environment & Safety
    # -----------------------------------------------------------------------
    "crime_rate": {
        "section": "Environment & Safety",
        "label": "Crime Rate",
        "description": "Crimes per 1,000 population per year",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "per 1,000/yr",
        "status": "core",
        "sort_priority": 1,
        "decision_question": "How safe does this area appear to be?",
        "metric_family": "crime",
        "interpretation_direction": "lower_is_better",
        "quality_notes": "Low-population areas may look artificially high.",
        "source_tables": ["core_crime_lsoa"],
    },
    "crime_trend": {
        "section": "Environment & Safety",
        "label": "Crime Trend (YoY)",
        "description": "Year-on-year change in crime rate",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": True,
        "map_binding": "none",
        "unit": "%",
        "status": "core",
        "sort_priority": 2,
        "decision_question": "Is local crime getting better or worse?",
        "metric_family": "crime",
        "interpretation_direction": "lower_is_better",
        "quality_notes": None,
        "source_tables": ["core_crime_lsoa"],
    },
    "flood_risk": {
        "section": "Environment & Safety",
        "label": "Flood Risk",
        "description": "Categorical flood risk level from EA flood zones",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "level",
        "status": "core",
        "sort_priority": 3,
        "decision_question": "How exposed is the area to flood risk?",
        "metric_family": "flood_risk",
        "interpretation_direction": "lower_is_better",
        "quality_notes": None,
        "source_tables": ["core_flood_lsoa"],
    },
    "air_quality_no2": {
        "section": "Environment & Safety",
        "label": "Air Quality (NO2)",
        "description": "Defra PCM grid NO2 concentration",
        "local_grain": "lad",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "µg/m³",
        "status": "core",
        "sort_priority": 4,
        "decision_question": "What is the air quality like here?",
        "metric_family": "air_quality",
        "interpretation_direction": "lower_is_better",
        "quality_notes": None,
        "source_tables": ["core_air_quality_lsoa"],
    },
    "air_quality_pm25": {
        "section": "Environment & Safety",
        "label": "Air Quality (PM2.5)",
        "description": "Defra PCM grid PM2.5 concentration",
        "local_grain": "lad",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "µg/m³",
        "status": "core",
        "sort_priority": 5,
        "decision_question": "What is the air quality like here?",
        "metric_family": "air_quality",
        "interpretation_direction": "lower_is_better",
        "quality_notes": None,
        "source_tables": ["core_air_quality_lsoa"],
    },
    "noise": {
        "section": "Environment & Safety",
        "label": "Noise Level",
        "description": "DEFRA strategic noise map — average road/rail/air decibel levels",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "dB",
        "status": "core",
        "sort_priority": 6,
        "decision_question": "How noisy is the area likely to feel?",
        "metric_family": "noise",
        "interpretation_direction": "lower_is_better",
        "quality_notes": None,
        "source_tables": ["core_noise"],
    },
    "green_cover": {
        "section": "Environment & Safety",
        "label": "Park Cover (1km)",
        "description": "Percentage green space within 1km. Postcode only",
        "local_grain": "postcode_only",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "%",
        "status": "core",
        "sort_priority": 7,
        "decision_question": "How green does the immediate area feel?",
        "metric_family": "green_space",
        "interpretation_direction": "higher_is_better",
        "quality_notes": "Only relevant to point-based searches.",
        "source_tables": ["core_green_space"],
    },
    "green_spaces": {
        "section": "Environment & Safety",
        "label": "Parks & Gardens in Area",
        "description": "Park count within area boundary. Area mode only",
        "local_grain": "area_only",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "count",
        "status": "core",
        "sort_priority": 7,
        "decision_question": "How much formal green space is available nearby?",
        "metric_family": "green_space",
        "interpretation_direction": "higher_is_better",
        "quality_notes": None,
        "source_tables": ["core_green_space"],
    },
    "nearest_park": {
        "section": "Environment & Safety",
        "label": "Nearest Park",
        "description": "Distance to nearest park. Postcode only",
        "local_grain": "postcode_only",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "metres",
        "status": "core",
        "sort_priority": 8,
        "decision_question": "How easy is it to reach a park on foot?",
        "metric_family": "green_space_access",
        "interpretation_direction": "lower_is_better",
        "quality_notes": "Only relevant to point-based searches.",
        "source_tables": ["core_green_space"],
    },
    "parks_1km": {
        "section": "Environment & Safety",
        "label": "Parks Within 1km",
        "description": "Park count within 1km. Postcode only",
        "local_grain": "postcode_only",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "count",
        "status": "core",
        "sort_priority": 9,
        "decision_question": "How many park options are within easy reach?",
        "metric_family": "green_space_access",
        "interpretation_direction": "higher_is_better",
        "quality_notes": "Only relevant to point-based searches.",
        "source_tables": ["core_green_space"],
    },
    "sports_recreation": {
        "section": "Environment & Safety",
        "label": "Sports & Recreation",
        "description": "Sports facility count within area or 1km",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "count",
        "status": "core",
        "sort_priority": 10,
        "decision_question": "How strong are the recreation options nearby?",
        "metric_family": "recreation",
        "interpretation_direction": "higher_is_better",
        "quality_notes": None,
        "source_tables": ["core_green_space"],
    },
    "epc_rating": {
        "section": "Environment & Safety",
        "label": "Average EPC Score",
        "description": "Weighted EPC score (duplicate of Property tab, different detail shape)",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "area_layer:choropleth_epc_score",
        "unit": "score",
        "status": "core",
        "sort_priority": 11,
        "decision_question": "How energy-efficient is the local housing stock?",
        "metric_family": "energy_efficiency",
        "interpretation_direction": "higher_is_better",
        "quality_notes": None,
        "source_tables": ["core_epc_lsoa"],
    },
    "esg_score": {
        "section": "Environment & Safety",
        "label": "ESG Score",
        "description": "Composite: EPC + air quality + flood + green space",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "score /100",
        "status": "core",
        "sort_priority": 12,
        "decision_question": "How strong is the area's overall environmental profile?",
        "metric_family": "environment_composite",
        "interpretation_direction": "higher_is_better",
        "quality_notes": None,
        "source_tables": ["core_epc_lsoa", "core_air_quality_lsoa", "core_flood_lsoa", "core_green_space"],
    },

    # -----------------------------------------------------------------------
    # Tab 4: Community & Education
    # -----------------------------------------------------------------------
    "demographics_overview": {
        "section": "Community & Education",
        "label": "Demographics Overview",
        "description": "Summary card with 8 sub-metrics. Sub-metrics have own parents",
        "local_grain": "lsoa",
        "supports_parent": False,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "people",
        "status": "core",
        "sort_priority": 0,
        "decision_question": "What kind of people and households live here?",
        "metric_family": "demographics",
        "interpretation_direction": "neutral",
        "quality_notes": None,
        "source_tables": ["core_census_lsoa"],
    },
    "population_density": {
        "section": "Community & Education",
        "label": "Population Density",
        "description": "Census population per hectare",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "people/hectare",
        "status": "core",
        "sort_priority": 1,
        "decision_question": "How dense or spacious does the area feel?",
        "metric_family": "demographics",
        "interpretation_direction": "neutral",
        "quality_notes": None,
        "source_tables": ["core_census_lsoa"],
    },
    "median_age": {
        "section": "Community & Education",
        "label": "Median Age",
        "description": "Census median age with age band breakdown",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "years",
        "status": "core",
        "sort_priority": 2,
        "decision_question": "Does the area skew younger, older, or balanced?",
        "metric_family": "demographics",
        "interpretation_direction": "neutral",
        "quality_notes": None,
        "source_tables": ["core_census_lsoa"],
    },
    "household_composition": {
        "section": "Community & Education",
        "label": "Household Composition",
        "description": "Census family/single/sharer percentages",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "% families",
        "status": "core",
        "sort_priority": 3,
        "decision_question": "What kinds of households dominate locally?",
        "metric_family": "households",
        "interpretation_direction": "neutral",
        "quality_notes": None,
        "source_tables": ["core_census_lsoa"],
    },
    "good_health": {
        "section": "Community & Education",
        "label": "Good Health",
        "description": "Census TS037 good/very good health percentage",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "%",
        "status": "core",
        "sort_priority": 4,
        "decision_question": "Does the resident health profile look relatively strong?",
        "metric_family": "health_profile",
        "interpretation_direction": "higher_is_better",
        "quality_notes": None,
        "source_tables": ["core_census_lsoa"],
    },
    "economically_active": {
        "section": "Community & Education",
        "label": "Economically Active",
        "description": "Census TS066 economic activity percentage",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "%",
        "status": "core",
        "sort_priority": 5,
        "decision_question": "How strong does local labour-market participation look?",
        "metric_family": "employment_profile",
        "interpretation_direction": "higher_is_better",
        "quality_notes": None,
        "source_tables": ["core_census_lsoa"],
    },
    "degree_educated": {
        "section": "Community & Education",
        "label": "Degree Educated",
        "description": "Census TS067 Level 4+ qualifications percentage",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "%",
        "status": "core",
        "sort_priority": 6,
        "decision_question": "How highly qualified is the local resident profile?",
        "metric_family": "education_profile",
        "interpretation_direction": "higher_is_better",
        "quality_notes": None,
        "source_tables": ["core_census_lsoa"],
    },
    "no_car": {
        "section": "Community & Education",
        "label": "No Car Household",
        "description": "Census TS045 no car/van availability percentage",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "%",
        "status": "core",
        "sort_priority": 7,
        "decision_question": "How car-dependent does local life appear to be?",
        "metric_family": "car_dependence",
        "interpretation_direction": "neutral",
        "quality_notes": "Higher may be positive in well-connected urban areas.",
        "source_tables": ["core_census_lsoa"],
    },
    "born_abroad": {
        "section": "Community & Education",
        "label": "Born Abroad",
        "description": "Census TS004 born outside UK percentage",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "%",
        "status": "core",
        "sort_priority": 8,
        "decision_question": "How internationally mixed is the local population?",
        "metric_family": "demographics",
        "interpretation_direction": "neutral",
        "quality_notes": None,
        "source_tables": ["core_census_lsoa"],
    },
    "wfh": {
        "section": "Community & Education",
        "label": "Works From Home",
        "description": "Census TS058 WFH percentage (also in Lifestyle tab)",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "%",
        "status": "core",
        "sort_priority": 9,
        "decision_question": "How remote-friendly does local work behaviour appear?",
        "metric_family": "commuting",
        "interpretation_direction": "higher_is_better",
        "quality_notes": None,
        "source_tables": ["core_census_lsoa"],
    },
    "housing_tenure": {
        "section": "Community & Education",
        "label": "Housing Tenure",
        "description": "Census owner-occupied/social rent/private rent split",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "% owner-occupied",
        "status": "core",
        "sort_priority": 10,
        "decision_question": "Is the local housing mix more owner-occupied or rental-led?",
        "metric_family": "housing_mix",
        "interpretation_direction": "neutral",
        "quality_notes": None,
        "source_tables": ["core_census_lsoa"],
    },
    "housing_type": {
        "section": "Community & Education",
        "label": "Housing Stock",
        "description": "Census detached/semi/terraced/flat split",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "% detached",
        "status": "core",
        "sort_priority": 11,
        "decision_question": "What kind of homes dominate the local housing stock?",
        "metric_family": "housing_mix",
        "interpretation_direction": "neutral",
        "quality_notes": None,
        "source_tables": ["core_census_lsoa"],
    },
    "household_size": {
        "section": "Community & Education",
        "label": "Household Size",
        "description": "Census 1/2/3-4/5+ person household split",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "% single-person",
        "status": "core",
        "sort_priority": 12,
        "decision_question": "Are local households smaller or larger than average?",
        "metric_family": "households",
        "interpretation_direction": "neutral",
        "quality_notes": None,
        "source_tables": ["core_census_lsoa"],
    },
    "ethnicity": {
        "section": "Community & Education",
        "label": "Ethnicity",
        "description": "Census ethnicity breakdown. Ward-level only",
        "local_grain": "ward",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "% White",
        "status": "core",
        "sort_priority": 13,
        "decision_question": "How mixed is the local ethnic profile?",
        "metric_family": "demographics",
        "interpretation_direction": "neutral",
        "quality_notes": "Ward-level data only.",
        "source_tables": ["core_census_ethnicity_ward"],
    },
    "religion": {
        "section": "Community & Education",
        "label": "Religion",
        "description": "Census religion breakdown. Ward-level only",
        "local_grain": "ward",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "% Christian",
        "status": "core",
        "sort_priority": 14,
        "decision_question": "What is the local religious composition?",
        "metric_family": "demographics",
        "interpretation_direction": "neutral",
        "quality_notes": "Ward-level data only.",
        "source_tables": ["core_census_religion_ward"],
    },
    "primary_schools": {
        "section": "Community & Education",
        "label": "Primary Schools",
        "description": "Outstanding/Good schools within 1mi (postcode) or area",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "point_layer:school",
        "unit": "count",
        "status": "core",
        "sort_priority": 14,
        "decision_question": "How strong is the local primary school offer?",
        "metric_family": "schools",
        "interpretation_direction": "higher_is_better",
        "quality_notes": None,
        "source_tables": ["core_schools"],
    },
    "secondary_schools": {
        "section": "Community & Education",
        "label": "Secondary Schools",
        "description": "Outstanding/Good schools within 3mi (postcode) or area",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "point_layer:school",
        "unit": "count",
        "status": "core",
        "sort_priority": 15,
        "decision_question": "How strong is the local secondary school offer?",
        "metric_family": "schools",
        "interpretation_direction": "higher_is_better",
        "quality_notes": None,
        "source_tables": ["core_schools"],
    },
    "deprivation": {
        "section": "Community & Education",
        "label": "IMD Deprivation",
        "description": "IMD 2025 score with rank, decile, 7 domain scores",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "score",
        "status": "core",
        "sort_priority": 16,
        "decision_question": "How deprived or advantaged does the area appear overall?",
        "metric_family": "deprivation",
        "interpretation_direction": "lower_is_better",
        "quality_notes": "Lower scores indicate less deprivation.",
        "source_tables": ["core_imd_lsoa"],
    },
    "nhs_facilities": {
        "section": "Community & Education",
        "label": "NHS Facilities (2km)",
        "description": "GP/dentist/pharmacy/optician/care home count",
        "local_grain": "lsoa",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "count",
        "status": "core",
        "sort_priority": 17,
        "decision_question": "How strong is local healthcare access?",
        "metric_family": "health_access",
        "interpretation_direction": "higher_is_better",
        "quality_notes": None,
        "source_tables": ["core_nhs_facilities"],
    },
    "area_persona": {
        "section": "Community & Education",
        "label": "Area Persona",
        "description": "Categorical label from persona scoring. Not comparable",
        "local_grain": "lsoa",
        "supports_parent": False,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "persona",
        "status": "persona_only",
        "sort_priority": 18,
        "decision_question": "What kind of area does this place most resemble?",
        "metric_family": "persona_inference",
        "interpretation_direction": "neutral",
        "quality_notes": None,
        "source_tables": ["core_census_lsoa"],
    },

    # -----------------------------------------------------------------------
    # Tab 5: Local Governance
    # -----------------------------------------------------------------------
    "council_tax": {
        "section": "Local Governance",
        "label": "Council Tax (Band D)",
        "description": "Band D council tax with all 8 bands",
        "local_grain": "lad",
        "supports_parent": True,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "GBP/year",
        "status": "core",
        "sort_priority": 1,
        "decision_question": "What are the ongoing local tax costs?",
        "metric_family": "local_governance",
        "interpretation_direction": "lower_is_better",
        "quality_notes": None,
        "source_tables": ["core_council_tax_lad"],
    },
    "local_authority": {
        "section": "Local Governance",
        "label": "Local Authority",
        "description": "Authority name. Categorical — not comparable",
        "local_grain": "lad",
        "supports_parent": False,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "name",
        "status": "core",
        "sort_priority": 2,
        "decision_question": "Which authority governs this area?",
        "metric_family": "local_governance",
        "interpretation_direction": "neutral",
        "quality_notes": None,
        "source_tables": ["core_lad_county_lookup"],
    },
    "controlling_party": {
        "section": "Local Governance",
        "label": "Controlling Party",
        "description": "Political party in control. Categorical — not comparable",
        "local_grain": "lad",
        "supports_parent": False,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "party",
        "status": "core",
        "sort_priority": 3,
        "decision_question": "Who currently controls the local council?",
        "metric_family": "local_governance",
        "interpretation_direction": "neutral",
        "quality_notes": None,
        "source_tables": ["core_council_control_lad"],
    },
    "water_company": {
        "section": "Local Governance",
        "label": "Water Company",
        "description": "Water provider name. Categorical — not comparable",
        "local_grain": "lad",
        "supports_parent": False,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "provider",
        "status": "core",
        "sort_priority": 4,
        "decision_question": "Which water company serves this area?",
        "metric_family": "utilities",
        "interpretation_direction": "neutral",
        "quality_notes": None,
        "source_tables": ["core_water_company_lad"],
    },
    "financial_health": {
        "section": "Local Governance",
        "label": "Financial Health (S114)",
        "description": "S114 notice status. Categorical — not comparable",
        "local_grain": "lad",
        "supports_parent": False,
        "supports_trend": False,
        "map_binding": "none",
        "unit": "status",
        "status": "core",
        "sort_priority": 5,
        "decision_question": "Are there obvious local-authority financial stress signals?",
        "metric_family": "local_governance",
        "interpretation_direction": "lower_is_better",
        "quality_notes": "Disabled pending replacement with provenance-backed source.",
        "source_tables": [],
    },
}

# ---------------------------------------------------------------------------
# Short labels and value types — enrichment for nested metric contract.
# These are kept as a companion mapping to avoid bloating the main registry
# dict with 2 extra fields × 60 entries. Applied at import time below.
# ---------------------------------------------------------------------------

_SHORT_LABELS = {
    # Tab 1: Property & Market
    "avg_price": "Avg price",
    "median_price": "Median price",
    "price_per_sqft": "£/sqft",
    "transaction_volume": "Transactions",
    "freehold_leasehold": "Freehold share",
    "new_build_proportion": "New-build share",
    "price_trend_yoy": "Price trend",
    "median_rent": "Median rent",
    "gross_yield": "Gross yield",
    "affordability": "Affordability",
    "median_earnings": "Median earnings",
    "investment_grade": "Investment grade",
    "epc_energy_score": "EPC score",
    "epc_rating_c_plus": "EPC C+ share",
    # Tab 2: Lifestyle & Connectivity
    "fifteen_min_score": "15-min score",
    "amenities_15min": "Amenities",
    "nearest_station": "Nearest station",
    "stations_in_area": "Stations",
    "ptal_score": "PTAL",
    "connectivity_index": "Connectivity",
    "ev_chargers": "EV chargers",
    "broadband": "Broadband",
    "full_fibre": "Full fibre",
    "superfast_broadband": "Superfast",
    "cycling": "Cycling",
    "commute_distance": "WFH rate",
    "mobile_coverage": "Mobile coverage",
    "mobile_4g_indoor": "4G indoor",
    "mobile_5g_outdoor": "5G outdoor",
    "commuter_connectivity": "Connectivity",
    # Tab 3: Environment & Safety
    "crime_rate": "Crime rate",
    "crime_trend": "Crime trend",
    "flood_risk": "Flood risk",
    "air_quality_no2": "NO₂",
    "air_quality_pm25": "PM2.5",
    "noise": "Noise",
    "green_cover": "Park cover",
    "green_spaces": "Parks",
    "nearest_park": "Nearest park",
    "parks_1km": "Parks nearby",
    "sports_recreation": "Sports",
    "epc_rating": "EPC score",
    "esg_score": "ESG score",
    "epc_rating_c_plus_env": "EPC C+ share",
    # Tab 4: Community & Education
    "demographics_overview": "Demographics",
    "population_density": "Density",
    "median_age": "Median age",
    "household_composition": "Households",
    "good_health": "Good health",
    "economically_active": "Econ. active",
    "degree_educated": "Degree educated",
    "no_car": "No car",
    "born_abroad": "Born abroad",
    "wfh": "WFH rate",
    "housing_tenure": "Tenure",
    "housing_type": "Housing stock",
    "household_size": "Household size",
    "ethnicity": "Ethnicity",
    "religion": "Religion",
    "primary_schools": "Primary schools",
    "primary_school_quality": "Primary quality",
    "secondary_schools": "Secondary schools",
    "secondary_school_quality": "Secondary quality",
    "deprivation": "IMD",
    "deprivation_income": "Income deprivation",
    "deprivation_employment": "Employment deprivation",
    "deprivation_education": "Education deprivation",
    "deprivation_health": "Health deprivation",
    "deprivation_crime": "Crime deprivation",
    "deprivation_barriers": "Barriers",
    "deprivation_living_environment": "Living env.",
    "nhs_facilities": "NHS",
    "area_persona": "Persona",
    # Tab 5: Local Governance
    "council_tax": "Council tax",
    "local_authority": "Authority",
    "controlling_party": "Ruling party",
    "water_company": "Water co.",
    "financial_health": "S114 status",
}

_VALUE_TYPES = {
    # Tab 1
    "avg_price": "currency", "median_price": "currency", "price_per_sqft": "currency_density",
    "transaction_volume": "rate", "freehold_leasehold": "percentage",
    "new_build_proportion": "percentage", "price_trend_yoy": "percentage_change",
    "median_rent": "currency", "gross_yield": "percentage", "affordability": "percentage",
    "median_earnings": "currency", "investment_grade": "categorical",
    "epc_energy_score": "score", "epc_rating_c_plus": "percentage",
    # Tab 2
    "fifteen_min_score": "score", "amenities_15min": "count",
    "nearest_station": "distance", "stations_in_area": "count",
    "ptal_score": "level", "connectivity_index": "score",
    "ev_chargers": "count", "broadband": "percentage",
    "full_fibre": "percentage", "superfast_broadband": "percentage",
    "cycling": "percentage", "commute_distance": "percentage",
    "mobile_coverage": "percentage", "mobile_4g_indoor": "percentage",
    "mobile_5g_outdoor": "percentage", "commuter_connectivity": "score",
    # Tab 3
    "crime_rate": "rate", "crime_trend": "percentage_change",
    "flood_risk": "level", "air_quality_no2": "scalar",
    "air_quality_pm25": "scalar", "noise": "scalar",
    "green_cover": "percentage", "green_spaces": "count",
    "nearest_park": "distance", "parks_1km": "count",
    "sports_recreation": "count", "epc_rating": "score",
    "esg_score": "score", "epc_rating_c_plus_env": "percentage",
    # Tab 4
    "demographics_overview": "categorical", "population_density": "rate",
    "median_age": "scalar", "household_composition": "percentage",
    "good_health": "percentage", "economically_active": "percentage",
    "degree_educated": "percentage", "no_car": "percentage",
    "born_abroad": "percentage", "wfh": "percentage",
    "housing_tenure": "percentage", "housing_type": "percentage",
    "household_size": "percentage", "ethnicity": "percentage", "religion": "percentage",
    "primary_schools": "count", "primary_school_quality": "percentage",
    "secondary_schools": "count", "secondary_school_quality": "percentage",
    "deprivation": "score", "deprivation_income": "score",
    "deprivation_employment": "score", "deprivation_education": "score",
    "deprivation_health": "score", "deprivation_crime": "score",
    "deprivation_barriers": "score", "deprivation_living_environment": "score",
    "nhs_facilities": "count", "area_persona": "categorical",
    # Tab 5
    "council_tax": "currency", "local_authority": "categorical",
    "controlling_party": "categorical", "water_company": "categorical",
    "financial_health": "categorical",
}

# Section name → stable section_id mapping (used in nested contract)
SECTION_IDS = {
    "Property & Market": "property_market",
    "Lifestyle & Connectivity": "lifestyle_connectivity",
    "Environment & Safety": "environment_safety",
    "Community & Education": "community_education",
    "Local Governance": "local_governance",
}

# Apply short_label and value_type to all registry entries at import time
for _mid, _entry in METRIC_REGISTRY.items():
    _entry.setdefault("short_label", _SHORT_LABELS.get(_mid, _entry.get("label", _mid)))
    _entry.setdefault("value_type", _VALUE_TYPES.get(_mid, "scalar"))
    _entry.setdefault("section_id", SECTION_IDS.get(_entry.get("section", ""), "general"))
